server:
  port: 8080

stats-server:
  url: http://stats-server:9090

logging:
  level:
    org:
      springframework:
        transaction:
          nodeValue: INFO
          interceptor: TRACE
        orm:
          jpa:
            nodeValue: INFO
            JpaTransactionManager: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: "true"
        show_sql: "true"
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm-db
    driverClassName: org.postgresql.Driver
    username: root
    password: root
---
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    url: jdbc:h2:mem:ewm-db
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console.enabled: true


